### ISSUE TITLE
question for attention_scores["omic"] 

### ISSUE THREAD

**Issue by jacobhqh1997** [mattiagualtieri/multimodal-path-omic#1]
Hello,I hope this message finds you well. I am currently working on replicating the MCAT visualization code like you, and I've come across some challenges.  In the official code(https://github.com/mahmoodlab/MCAT/blob/master/Model%20Computation%20%2B%20Complexity%20Overview.ipynb).
        attention_scores = {'coattn': A_coattn, 'path': A_path, 'omic': A_omic} ###forward part
I noticed that the attention_scores dictionary contains the following shapes
`print(attention_scores["coattn"].shape)  # torch.Size([1, 1, 6, 15231])
print(attention_scores["path"].shape)     # torch.Size([1, 6])
print(attention_scores["omic"].shape)     # torch.Size([1, 6])`

It seems that attention_scores["omic"] represents the attention scores for each gene set. However, I am trying to understand how to extract the attention scores for individual genes within each gene set, as depicted in the original code.
![Uploading temp.PNG…]()
I would greatly appreciate any guidance or insights you could provide on this matter. Thank you for your time!

**Comment by jacobhqh1997** [comment]
![Uploading temp.PNG…]()

**Comment by jacobhqh1997** [comment]
![temp](https://github.com/user-attachments/assets/6f547b55-0265-44c9-98af-5045669fe65c)

**Comment by ggutim** [comment]
Hi @jacobhqh1997, reading the supplemental material it seems that they didn’t use attention scores to infer single genes attention, but they used a technique called **Integrated Gradients**. From the supplemental material of MCAT:

> To assess gene attribute and genomic embedding feature importance, we used Integrated Gradients (IG) [[Axiomatic Attribution for Deep Networks](https://arxiv.org/abs/1703.01365)] a gradient-based feature attribution method that attributes how prediction are made by the model with respect to the inputs.

I still haven’t implemented this feature, and honestly I'm not sure if I'm going to. It depend if I've enough time for my thesis!

**Comment by jacobhqh1997** [comment]
> Hi @jacobhqh1997, reading the supplemental material it seems that they didn’t use attention scores to infer single genes attention, but they used a technique called **Integrated Gradients**. From the supplemental material of MCAT:
> 
> > To assess gene attribute and genomic embedding feature importance, we used Integrated Gradients (IG) [[Axiomatic Attribution for Deep Networks](https://arxiv.org/abs/1703.01365)] a gradient-based feature attribution method that attributes how prediction are made by the model with respect to the inputs.
> 
> I still haven’t implemented this feature, and honestly I'm not sure if I'm going to. It depend if I've enough time for my thesis!

thank you for your quick reply, I will try it. Have a nice day!@mattiagualtieri

**Comment by ggutim** [comment]
@jacobhqh1997 feel free to contribute to the repo if you want! Have a nice day too.
